### ISSUE TITLE
章节顺序错乱

### ISSUE THREAD

**Issue by hgcjd666666** [FrankMilesFrms/KMaoDecode#1]
[详见此文件（密码：黄金）](https://www.lanzouj.com/i68Jo15vuyqd)

**Comment by hgcjd666666** [comment]
![Screenshot_20230820_130834_bin mt plus canary](https://github.com/FrankMilesFrms/KMaoDecode/assets/99111893/15d93468-1982-4b2e-a8dc-0528d3259edf)
![Screenshot_20230820_130910_com kmxs reader](https://github.com/FrankMilesFrms/KMaoDecode/assets/99111893/596e43b5-fec9-4152-8077-1124d259d7b3)
![Screenshot_20230820_130909_com kmxs reader](https://github.com/FrankMilesFrms/KMaoDecode/assets/99111893/7ba087ef-82ae-4b66-b34d-6176be400da1)
![Screenshot_20230820_130901_com kmxs reader](https://github.com/FrankMilesFrms/KMaoDecode/assets/99111893/93d732ec-fbea-4da8-84cb-f050a3b24a69)
![Screenshot_20230820_130849_bin mt plus canary](https://github.com/FrankMilesFrms/KMaoDecode/assets/99111893/5f3acbbf-2520-44c4-997a-5101008c0d62)

**Comment by FrankMilesFrms** [comment]
问题我已知悉，将会重定义章节排序，稍后会以邮件的方式与你取得进一步联系！

**Comment by hgcjd666666** [comment]
> 问题我已知悉，将会重定义章节排序，稍后会以邮件的方式与你取得进一步联系！

邮箱：hgcjd666@qq.com

**Comment by FrankMilesFrms** [comment]
好的，我将会给你发一份重排序文本，请注意该邮件是否能解决问题。

**Comment by FrankMilesFrms** [comment]
文件已经经过整理，请检查邮箱，注意是否正序，感谢你的反馈。
