### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Wenmoux** [FrankMilesFrms/KMaoDecode#2]
点击生成就会闪退 无提示_(•̀ω•́ 」∠)_

**Comment by FrankMilesFrms** [comment]
请告诉我，是否可复现、你的详细操作方式？另外，请你提供设备型号、安卓版本，以及书籍名称。

**Comment by Wenmoux** [comment]
百分百出现

目标文件夹: /sdcard/xx/xx/
输出 /sdcard/wen/a.txt

正常点完生成就闪退了

书名 我和软萌女友的恋爱日常
设备 魅族18pro
安卓11

**Comment by FrankMilesFrms** [comment]
经过全本下载测试，测试型号：M11，内存8G，读取路径：/sdcard/<书籍文件夹名>，输出路径：/sdcard/a.txt，debug模式下，一切正常。
推测：你的手机内存是否不足？读取路径是否存在于特殊文件夹下，比如/Android/、/DICM....等？

**Comment by FrankMilesFrms** [comment]
我已发布新版本，请使用“低内存模式”生成测试，是否有所好转。
