### ISSUE TITLE
安卓11卡退

### ISSUE THREAD

**Issue by XIXaa** [FrankMilesFrms/KMaoDecode#3]

**Comment by FrankMilesFrms** [comment]
@66454 
你好，请详细描述一下，你是怎么触发BUG的。

-  如果是进入闪退，请列出手机详细信息，以便修复。

-  如果生成数据闪退，请详细列出你操作的步骤、手机详细信息，并请压缩后上传导入的数据源，或以邮件发送至FrankMiles@qq.com

 详细说明有助于我尽快修复问题，再次感谢你的回复。

**Comment by XIXaa** [comment]
[MobileFile.zip](https://github.com/FrankMilesFrms/KMaoDecode/files/12909157/MobileFile.zip)
入/sdcard/1/219695/
出/sdcard/1/219695/1/
不点低内存点保存配置会卡退，点了低内存不卡退但不会生成文章，生成文章数是0

**Comment by FrankMilesFrms** [comment]
@66454 你好，麻烦你将219695整个文件夹压缩后上传。

**Comment by XIXaa** [comment]
[219695.zip](https://github.com/FrankMilesFrms/KMaoDecode/files/12909171/219695.zip)

**Comment by FrankMilesFrms** [comment]
@66454 问题已经复现，稍后我将会修复问题并通知您吗，感谢您的回复。

**Comment by FrankMilesFrms** [comment]
感谢你的回复，问题已经复现。

**Comment by FrankMilesFrms** [comment]
@66454 你好，问题已经得到修复，如有新的问题，你可以随时提交，再次感谢你的回复。
